app/assets/stylesheets/proposal.css.scss

Previously if you have a short header, you get this:
This change makes the header span the entire block:
Another alternative would be to add right margin for h1 headers.

h1 proposals should span entire block

---

app/decorators/session_decorator.rb
app/views/organizer/sessions/_sessions.html.haml

DataTables was throwing an error because the row data being provided for the newly added session was missing the ID column. The fix was to add the session id to the SessionDecorator#row_data method.

Fix DataTables Error When Adding New Sessions

---

app/assets/stylesheets/_base.css.scss
app/views/events/show.html.haml
app/views/proposals/_comments.html.haml
app/views/proposals/_contents.html.haml

Hi! Rustcamp is using this app to do its CFP process, and the lack of bullets displaying in the rendered markdown was getting to me, so I fixed it! :sparkling_heart: 
It's hard to read ul elements when the list-style-type is none, and I expected markdown-enabled input fields to create bulleted lists in the generated output.
I added a class `markdown` around places in the interface that render entered markdown and set the ul list-style-type to disc within those elements.
Thank you!!! :heart: :heart_decoration: :heart: :heart_decoration:

Show bullets for ul elements created from markdown.

---

app/controllers/admin/people_controller.rb

If administrator update of a Person fails, an error is thrown due to access of local var `person` (which should be instance var `@person`). This PR has the fix.

Fix for Admin::PeopleController#update: local var to instance var;

---

app/controllers/reviewer/proposals_controller.rb
app/decorators/event_decorator.rb
app/models/event.rb
app/models/proposal.rb
app/views/reviewer/proposals/index.html.haml

Proposals that have been withdrawn should not be part of the total number of proposals to be rated
On reviewer's page, withdrawn proposals should be removed. Organizers can see all proposals, including withdrawn.
@mgarriott @Kel4545 when you get a chance, can you review? thanks!

#8: withdrawn proposals are not shown to reviewers

---

app/models/event.rb
app/views/events/show.html.haml

Guidelines should be visible regardless of if the event is open or closed
@mgarriott can you take a look when you have a chance? thanks!

#10 Guidelines should be visible

---

app/models/person.rb
app/models/service.rb
db/migrate/20151217214608_add_account_name_to_service.rb
db/schema.rb
spec/models/person_spec.rb

Several users have complained that they cannot log into their accounts after an unspecified elapsed time. We believe this is as a result of Twitter and Github returning different user ids for the account when using the oAuth authentication.
This change adds an account_name field to the Service model in which we will now save the returned Github account name or Twitter handle. In the event that looking up a service by UID fails, we will then try to look up the service by account name instead. We'll also now update a found service with any new information.
Unrelated, but still in this change, I fixed a failing spec app/models/person_spec:251. This spec was failing due to a previous change that added a validation to the Participant model.

Save oauth account_name for fallback service lookups

---

db/migrate/20130922231603_create_invitations.rb
db/schema.rb

Hi! I would like to use this for reddotrubyconf.com and so upon cloning the repo, the first thing I did was `rake db:create db:migrate`, but it error out with:
```
== 20130922231603 CreateInvitations: migrating ================================
-- create_table(:invitations)
-> 0.0139s
-- add_index(:invitations, [:proposal_id, :email], {:unique=>true})
-> 0.0030s
-- add_index(:invitations, :slug, {:unique=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
Index name 'index_invitations_on_slug' on table 'invitations' already exists/Users/winston/workspace/cfp-app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:939:in `add_index_options' …
```

Fix migration and update schema

---

app/controllers/organizer/proposals_controller.rb
app/controllers/reviewer/proposals_controller.rb
app/decorators/person_decorator.rb
spec/decorators/person_decorator_spec.rb

Whenever I run specs, I see this deprecation warning:
```
DEPRECATION WARNING: The method `proposal_path` cannot be used here as a full URL is required. Use `proposal_url` instead. (called from proposal_path at /Users/winston/workspace/cfp-app/app/decorators/person_decorator.rb:14)
```
Also, I see a comment in `app/decorators/person_decorator.rb` and I am not sure if it's meant to be a signal for "Don't fix" or "TODO". Hence I went ahead to fix to the deprecation warning by updating `*_path` to `*_url` in `app/decorators/person_decorator.rb`.
This however broke some specs, and so I fixed those specs as well to use `*_url`. 
Is there some history to this? Or would this change be acceptable? Thank you!

Fix deprecation warning and update specs

---

app/assets/stylesheets/_base.css.scss
app/views/proposals/show.html.haml
db/schema.rb

Make finding the link to the event along with its date very obvious to speakers
Resolves this issue: "It's very hard to find the link to the event itself or the date of the event anywhere. I was confirming my proposal and had hard time remembering when the actual NYC.rb was"

16 - Make event link and dates clear to speakers

---

README.md
bin/setup

- `bin/setup` more information: https://github.com/rails/rails/pull/15189
- Use `bin/rails` to take advantage of Spring
http://guides.rubyonrails.org/4_1_release_notes.html#spring-application-preloader
- Remove the mention of copy `config/database_example.yml` in README.md
Since it does not exist anymore, removed in bcfe938

Make setup for project easier with bin/setup script

---

app/controllers/sessions_controller.rb

Trying to logout right after logging in causes you to be redirected back to the oauth callback url, which returns 401 (for Twitter) or csrf_error (for Github).  You also get the flash message from logging in when you navigate manually back to the root path.  Both easy fixes.

Fixed bug causing 401 or csrf_error on logout and mistaken flash message.

---

app/models/proposal.rb

I noticed an unassigned ```@dont_touch_updated_by_speaker_at``` variable at line 205.  It doesn't appear to be doing anything.

remove errant variable in proposal.rb

---

README.md
bin/setup
config/database.yml

After walking through the new CFP 2.0 app to test how the Readme has aged and how smoothly setup goes. 
The answer: Not bad, but the QT stuff is frustrating to install. v2.0 looks great, though!
There is a coming PR to switch `capybara-webkit` out -> https://github.com/rubycentral/cfp-app/pull/133

Updates to the Readme for clarity around the v2.0 upgrade

---

app/controllers/staff/events_controller.rb
app/models/event.rb

The issue happens after a CFP has closed and the organizer wants to save or update a speaker email template.  We're not sure how appropriate the validation check on having a closes_at date that is in the future.  It makes sense when you're initially creating an event but makes zero sense after it's been closed.  I decided to just remove the check altogether.  I'll just trust organizers to set closes_at dates appropriately.
This error also exposed the fact that our render on errors never worked due to an incorrect template path.

Fix error with saving speaker email templates

---

CONTRIBUTING.md
app/views/proposals/_comments.html.haml

When reading a proposal's comments with a screen reader, it reads out
the entire timestamp of a comment, like `2019-01-02 20:33:56 -0800`.
When read out loud, this takes a long time, is disruptive to the reading
experience, and sounds a bit silly.
Further, this timestamp is nowhere on the page and doesn't seem to serve
a purpose.
Instead, this PR removes the `title` field on each proposal comment.
This way, when entering the comment section, a user hears the "X
[Public/Internal] Comments" header, then is able to dive directly into
each comment itself. This content flow is much smoother, making for a
better user experience.
I also fixed some broken code snippets in `CONTRIBUTING.md`. The git
remotes did not point to git repositories, and the org name was incorrectly
listed as …

Accessibility: remove proposal comment titles

---

app/views/profiles/edit.html.haml

Currently, there is no intuitive way from the CFPApp itself to know where the profile icon is obtained from, and how to either add or change it. People for a variety of reasons may want to change their profile image on CFPApp from the time they first opened an account, and as it stands now, there is no clear path to do that easily. 
In this pull request, a new section is added to the `Edit Profile` view, which provides a link to either add or edit one's profile image hosted on Gravatar, which is where CFPApp receives it from. This new feature is an enhancement of the user experience.

[New feature] Link to add/edit Gravatar profile icon in Edit Profile view

---

app/models/proposal.rb
spec/models/proposal_spec.rb

The abstract length was originally 600 characters. Carriage return
characters would typically be included in the standard length
validation, so the limit was increased to 1000. This commit creates a
custom validation to strip out the carriage return characters and count
the resulting string length. If _THAT_ is greater than 600 characters
then there is an error.

Redo proposal abstract length validation

---

Gemfile
Gemfile.lock
Procfile
app/controllers/staff/proposals_controller.rb
app/jobs/application_job.rb
app/jobs/bulk_finalize_job.rb
config/application.rb
config/environments/test.rb
spec/features/staff/organizer_finalizes_proposals_spec.rb

Use ActiveJob to bulk finalize and send email. That way we don't time
out the web request. (#147)

Offload bulk finalize to a background worker

---

app/helpers/staff_helper.rb
app/views/shared/proposals/_tags_form.html.haml
app/views/staff/proposal_reviews/show.html.haml
app/views/staff/proposals/show.html.haml

Tags can be a helpful way to organize talks into buckets as they are
being evaluated and accepted. They can also be useful for categorizing
talks when creating the schedule to make sure you have a good balance
across days and rooms. This allows tags to be updated after a talk has
been finalized. #146

Allow updating tags after proposal is finalized

---

.gitignore
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/concerns/activate_navigation.rb
app/controllers/staff/websites_controller.rb
app/helpers/application_helper.rb
app/models/event.rb
app/models/speaker.rb
app/models/website.rb
app/policies/website_policy.rb
app/views/layouts/_navbar.html.haml
app/views/layouts/nav/staff/_website_subnav.html.haml
app/views/staff/websites/_form.html.haml
app/views/staff/websites/edit.html.haml
app/views/staff/websites/new.html.haml
config/routes.rb
db/migrate/20220412104802_create_websites.rb
db/schema.rb
spec/factories/websites.rb
spec/features/website/configuration_spec.rb
spec/policies/website_policy_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb

This PR covers a very minimal feature of an "Organizer Creating a Event Website". It merely builds out the initial model and some basic routes, controller, views and authorization that will be built upon in upcoming PRs.
The Website model, while currently just an association to the Event model, will soon be used for data and logic needed for configuration of the website. It also will help keep the logic and associations related to the website generation and presentation isolated from the Event god object. 
The PR tries to mostly follow existing patterns (e.g. navigation/sub-navigation) without getting lost in possible refactorings. However, the [decent_exposure](https://github.com/hashrocket/decent_exposure) gem was added for developer happiness. 
- adds Website model and belongs_to …

Organizer Creates Event Website

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/modules/_navbar.scss
app/controllers/concerns/activate_navigation.rb
app/controllers/staff/pages_controller.rb
app/javascript/controllers/editor_controller.js
app/javascript/controllers/index.js
app/javascript/packs/application.js
app/models/page.rb
app/models/website.rb
app/policies/page_policy.rb
app/views/layouts/nav/staff/_website_subnav.html.haml
app/views/staff/pages/_form.html.haml
app/views/staff/pages/_page.html.haml
app/views/staff/pages/edit.html.haml
app/views/staff/pages/index.html.haml
app/views/staff/pages/new.html.haml
config/routes.rb
db/migrate/20220412153740_create_pages.rb
db/schema.rb
package.json
spec/features/website/page_management_spec.rb
spec/policies/page_policy_spec.rb
spec/support/helpers.rb
spec/support/helpers/form_helpers.rb
yarn.lock

Organizer Adds Website Page
This PR sets up the page object for organizers to create and update. Fields for both `unpublished_body` and `published_body` are included though only currently the former is being used. The ability to view the page content and the ability to preview and publish will come in future PRs. 
WYSIWYG editing for the page content is currently being done with TinyMCE which can be a bit tricky to figure out the best way to install and configure. Trix was considered as an alternative but during the spike some challenges were bumped into the opinionated way that it sanitized and marked up the html. Additionally, TinyMCE has a plugin for editing the html code which may prove valuable to developers skilled with html and css. Unfortunately …

Organizer Adds Website Page

---

app/controllers/staff/pages_controller.rb
app/policies/page_policy.rb
app/views/staff/pages/_page.html.haml
app/views/staff/pages/preview.html.haml
config/routes.rb
spec/features/website/page_management_spec.rb
spec/policies/page_policy_spec.rb

Organizer Previews Website Page
This PR builds on the publishing of a website page by providing a backend preview view of the unpublished content before it gets published. 
Changes
=======
- adds preview page for unpublished_body using iframe with frontend
layout
- fixes button styles for publishing button as well
[Miro Card](https://miro.com/app/board/uXjVOA-0gUs=/?moveToWidget=3458764523048559109&cot=14)
[PR Review App](https://cfp-app-flagrant-websit-zdg1dq.herokuapp.com/)

Organizer Previews Website Page

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/controllers/staff/pages_controller.rb
app/controllers/staff/websites_controller.rb
app/helpers/website_helper.rb
app/models/page.rb
app/models/website.rb
app/policies/page_policy.rb
app/views/layouts/themes/default.html.haml
app/views/staff/pages/_page.html.haml
app/views/staff/pages/index.html.haml
app/views/staff/websites/_form.html.haml
config/environments/development.rb
config/initializers/domain_constraint.rb
config/routes.rb
db/migrate/20220414014639_add_domains_to_websites.rb
db/migrate/20220415014232_add_landing_to_pages.rb
db/schema.rb
spec/features/website/configuration_spec.rb
spec/features/website/page_management_spec.rb
spec/features/website/page_viewing_spec.rb
spec/models/page_spec.rb
spec/models/website_spec.rb
spec/policies/page_policy_spec.rb

Organizer Selects Landing Page 
This PR allows an organizer to select which page will serve as the landing page for the website. The thought is that when an event is first announced there will likely be a different page to serve as the landing page than when registration starts and the conference begins. 
Moreover, this PR hopefully improves some of the routing complexity needed in order to host multiple websites using custom domains without also getting tangled in the home page for CFP app itself. One challenge the PR hopefully addresses is a possible conflict between routes like `railsconf.org/about` which should route to the latest Railsconf about page and `railsconf.org/railsconf-2021` which should route to the landing page for an older Railsconf …

Organizer Selects Landing Page 

---

app/models/program_session.rb
spec/models/program_session_spec.rb

Recently, we had a speaker cancel their presentation, but the session had already been scheduled in the app.
In prod, I deleted the `ProgramSession` using the dedicated button in the UI to do so, but then got some errors when trying to view the schedule.
This was because there was still a `TimeSlot` referencing the deleted `ProgramSession`.
Changes
=======
When deleting a `ProgramSession`, nullify the `program_session_id` on the related `TimeSlot` if applicable.
Also cleaned up some specs while I was in there.

Nullify a ProgramSession's TimeSlot

---

Gemfile
Gemfile.lock
app/assets/stylesheets/modules/_staff-website-page.scss
app/controllers/image_uploads_controller.rb
app/javascript/controllers/editor_controller.js
app/javascript/packs/application.js
app/javascript/stylesheets/application.scss
app/views/layouts/application.html.haml
app/views/staff/pages/_form.html.haml
config/environments/production.rb
config/initializers/active_storage.rb
config/routes.rb
config/storage.yml

Use Images In Content
From Miro Card: 
> As a content creator I may want to upload images inline to content I'm creating, or link to an externally hosted image. I'd like this process to be easy and not require committing things to Github.
Note that this PR builds on a previous PR [Wireframe website layout](https://github.com/rubycentral/cfp-app/pull/273). While deploying this branch to staging it was revealed that CodeMirror css needed to be imported and included differently with Webpacker in production environment so this PR resolves that as well. 
Changes
=======
- adds ability to upload images from tinymce editor
- allows svg images to be uploaded and to not be treated as binary
- updates preview when image is uploaded or removed with change event …

Use Images In Content

---

app/assets/stylesheets/themes/default/application.scss
app/assets/stylesheets/themes/default/nav.scss
app/assets/stylesheets/themes/default/sponsors.scss
app/controllers/sponsors_controller.rb
app/javascript/controllers/banner_ads_controller.js
app/models/sponsor.rb
app/views/sponsors/banner_ads.html.haml
app/views/sponsors/show.html.haml
config/routes.rb

🟡  - Still needs a feature spec. 
The conference websites allowed event sponsors to display banner ads across various website pages. This PR seeks to enable that feature on the event website. 
Website creators/designers will be able to add a specific html stimulus controller to any page body, and that page will display a rotating sponsor banner ad element. 
Changes
=======
- adds a route at the sponsors controller at 'website/banner_ads'
- adds stimulus controller that will query the banner_ad route
- adds a template for the banner_ads route, that will be seeded by the event sponsors with a banner_ad
The element that will enable the sponsors banner would look like
```
<div data-controller="banner-ads" …
```

sponsor banner ad stimulus controller

---

app/assets/stylesheets/modules/_staff-website-page.scss
app/controllers/sponsors_controller.rb
app/controllers/staff/pages_controller.rb
app/decorators/website_decorator.rb
app/helpers/page_helper.rb
app/javascript/controllers/banner_ads_controller.js
app/javascript/controllers/editor_controller.js
app/views/pages/show.html.haml
app/views/sponsors/banner_ads.html.haml
app/views/sponsors/sponsors_footer.html.haml
app/views/staff/pages/_form.html.haml
config/routes.rb
spec/factories/sponsors.rb
spec/features/website/sponsor_spec.rb

While thinking about page caching I was feeling concerned about the complexity of having the sponsor banner adds and footer components being loading asynchronously. It suddenly occurred to me that we could easily be rendering those server side with a simple `gsub` of custom tags. This also had the added benefit of making the tags much simpler for a content editor to add to the page. Unfortunately though it led me down some rabbit holes but hopefully led to some improvements.
First of all previewing of pages with banners or footers while editing broke because we were just swapping out the html in the iframe. I found an interesting solution of instead making a request from a hidden form with the iframe as the target (I did not know you could do this but …

Editor Improvements

---

app/controllers/staff/pages_controller.rb
app/decorators/website_decorator.rb
app/models/page.rb
app/views/layouts/themes/default.html.haml
app/views/staff/pages/_form.html.haml
db/migrate/20220503085207_add_hiding_fields_to_pages.rb
db/schema.rb
spec/features/website/page_management_spec.rb

This PR adds two different boolean fields on Page to help control its visibility in the website. `Page#hide_navigation` will just remove a page from the navigation. This will allow a page like a Splash page or some less significant content page to be published but not take up space in the navigation. On the other hand there is also now a `Page#hide_page` flag that will essentially unpublish a page such that it cannot be visible to the public. 
Changes
=======
- adds Page#hide_navigation and #hide_page boolean
- adds hide_page: false condition to published scope
- adds WebsiteDecorator#navigation_page_names_and_slugs for more
efficient generation of navigation links with just names and slugs
[Unpublish a page/hide …

Adds ability to remove page from navigation and/or hide it entirely

---

app/assets/javascripts/base.js
app/assets/stylesheets/modules/_code-mirror.scss
app/assets/stylesheets/themes/default/application.scss
app/assets/stylesheets/themes/default/footer.scss
app/controllers/staff/pages_controller.rb
app/controllers/staff/websites_controller.rb
app/decorators/website_decorator.rb
app/models/page.rb
app/models/website.rb
app/views/layouts/themes/default/_footer.html.haml
app/views/layouts/themes/default/_header.html.haml
app/views/staff/pages/_form.html.haml
app/views/staff/pages/_page.html.haml
app/views/staff/pages/index.html.haml
app/views/staff/pages/themes/default/splash.html.erb
app/views/staff/websites/_form.html.haml
db/migrate/20220504213512_add_navigation_links_to_websites.rb
db/schema.rb
spec/features/website/configuration_spec.rb
spec/features/website/page_management_spec.rb
spec/features/website/page_viewing_spec.rb

Control the order of navigation links
From Miro Story: 
>As a designer, I need to be able to determine the ordering of navigation links, so that I can control the layout of navigation on the site. This lets me put important links first.
This PR cleverly uses selectize along with the included drag-and-drop plugin to select and order both the static and dynamic pages to control the visibility and order of the navigation links. Hopefully this simplifies the navigation management. 
While working on the navigation links I recognized that using a select gets selectize to submit the values as an array which I was able to similarly use to cleanup `Website#footer_categories`. 
Changes
=======
- adds ability to select and sort order of static and dynamic pages to …

Control the order of navigation links

---

app/assets/stylesheets/modules/_forms.scss
app/assets/stylesheets/themes/default/application.scss
app/assets/stylesheets/themes/default/program.scss
app/controllers/staff/websites_controller.rb
app/decorators/website_decorator.rb
app/helpers/website_helper.rb
app/javascript/controllers/editor_controller.js
app/javascript/controllers/nested_form_controller.js
app/models/session_format_config.rb
app/models/website.rb
app/models/website/font.rb
app/views/layouts/themes/default.html.haml
app/views/schedule/show.html.haml
app/views/staff/websites/_font_fields.html.haml
app/views/staff/websites/_form.html.haml
db/migrate/20220506044703_create_table_website_fonts.rb
db/schema.rb
spec/features/website/schedule_spec.rb

Title
From Miro Card: 
>As a designer, I want to be able to change the typography of the site. This might involve a primary and a secondary typeface. I want changes I make in one place to be reflected across the whole site, both in static and dynamic pages.
This PR introduces a new model to capture information about website fonts and store typeface files. These font files are then dynamically loaded into the head using style tags.
Also, a new  StimulusJS `nested_form_controller` was added to help manage adding, editing and removing of fonts nested in the Website configuration form page. This was mostly stolen from [GoRails](https://github.com/gorails-screencasts/dynamic-nested-forms-with-stimulusjs/blob/master/app/javascript/controllers/nested_form_contr …

Change the typography of the site

---

app/controllers/staff/websites_controller.rb
app/decorators/website_decorator.rb
app/helpers/image_helper.rb
app/models/website.rb
app/models/website/meta_data.rb
app/views/layouts/themes/default.html.haml
app/views/pages/show.html.haml
app/views/programs/show.html.haml
app/views/schedule/show.html.haml
app/views/sponsors/show.html.haml
app/views/staff/websites/_form.html.haml
db/migrate/20220508071747_create_website_meta_data.rb
db/schema.rb
spec/features/website/configuration_spec.rb

From Miro Story: 
>Current site includes opengraph (prefixed og:) metadata and twitter metadata. Title tags should be distinct and based on the page name.
At first I was considering a more flexible approach to adding metadata tags but in the end that was going to not be worth the complexity. This approach provides inputs for the minimal needed information to duplicate the current tags represented in the old railsconf layout.
Changes
- adds Website::MetaData for storing information to populate og and
twitter meta tags
- adds Website#favicon attachment
- refactors image input to helper method
- adds title to dynamic and static pages
[Basic metadata for SEO](https://miro.com/app/board/uXjVO6C1LxA=/?moveToWidget=3458764523894399447&cot=14)

Basic metadata for SEO

---

app/controllers/staff/pages_controller.rb
app/controllers/staff/websites_controller.rb
app/models/website.rb
app/models/website/font.rb
app/views/staff/websites/_form.html.haml
spec/features/website/configuration_spec.rb
spec/features/website/page_management_spec.rb

This PR addresses some issues that arose during early testing of website configuration and page creation. 
Changes
=======
- skips font creation when name and file are blank
- adds validation to ensure font name and file are present
- renders :new and :edit with flash message when creating and updating
fail
- redirects to new website page with message when accessing pages before
website is configured
- adds regression specs for above scenarios
Title

Website fonts and pages bugfixes

---

app/decorators/website_decorator.rb
spec/features/website/configuration_spec.rb
spec/features/website/page_management_spec.rb

Devon noticed the following buggy behavior: 
>This is a small thing that I've noticed - doesn't seem to impact the published page (which is good). I keep trying to reorder "Home" to be the first link in the nav. Click save. See published page and notice "Home" is where I expect (good). Then, I go back to the config page and see that Home has decided to reorder itself again. Just a weird blip of thing - but not too big of a deal." ~Devon in Slack 5/11
While the order was being persisted in the database the link options were reordering the selectize values which would have unintentionally reordered the navigation links on a subsequent save. This PR makes sure that the link options match the order of the selected links so that selectize does not reorder …

Navigation link ordering does not persist

---

app/decorators/website_decorator.rb
app/helpers/image_helper.rb
app/helpers/page_helper.rb
app/helpers/website_helper.rb
app/views/staff/pages/_form.html.haml
app/views/staff/pages/index.html.haml
app/views/staff/pages/new.html.haml
app/views/staff/pages/themes/default/home.html.erb
app/views/staff/pages/themes/default/splash.html.erb
app/views/staff/websites/_form.html.haml
docs/website_documentation.md
spec/features/website/configuration_spec.rb
spec/features/website/page_management_spec.rb

While using the app Devon noticed that if you add a logo or background image to a static page and then change those images you need to update the urls in the pages to keep them in sync. This resolves that by using special custom tags that will embed the most recent images dynamically into the page. It also switches the templates to use these new tags. 
Changes
=======
- Adds ability to embed the logo image or background image to a page
- Updates templates to use custom dynamic tags
- Updates website documentation about custom logo and background tags

Dynamic Logo/Background Image

---

app/decorators/staff/time_slot_decorator.rb
app/views/staff/time_slots/_time_slots.html.haml

In order for an event organizer to better track which time slots are assigned sponsors, include a sponsor star on the time slot index page
Changes
=======
* Minimal changes. 1 method in the decorator
Quick Preview
===========

indicate sponsored time slots on time slot index

---

app/controllers/staff/pages_controller.rb
app/models/page.rb
app/models/website.rb
app/views/staff/pages/_page.html.haml
app/views/staff/pages/index.html.haml
db/migrate/20220523185412_add_body_published_at_to_pages.rb
db/schema.rb
spec/factories/pages.rb

🟡  - Ready for Review
As a website editor I would like to know when a page was last edited, and which pages have updates that have yet to be published
Changes
=======
- add body_published_at column to the pages table.
- when a page is published, set the value of body_published_at.
- If a page has unpublished changes, display this on the index with an icon.
Who Doesn't Love a Preview
=====================

add body_published_at to pages table

---

app/models/website.rb
spec/models/website_spec.rb

While configuring domains for rubyconf it was discovered that only the last domain in the list was being matched correctly which revealed the bug in the Postgres match string.
Changes
=======
- adds wildcard to the end of the ILIKE match string and removes
unneeded parens around interpolated domain

Fixes bug with matching website with multiple domains configured

---

app.json

Title
* After upgrading to Ruby 3.0.4 and upgrading via dashboard to `heroku-22` buildpack, the build failed.
* That version of Ruby is only in `heroku-20`.
Changes
=======
* Specify the buildpack in `app.json`
Documentation
=============
* https://devcenter.heroku.com/articles/heroku-20-stack#using-heroku-20

Specify Heroku buildpack 'heroku-20'

---

app/controllers/programs_controller.rb
app/controllers/schedule_controller.rb
app/controllers/sponsors_controller.rb
app/models/website.rb
spec/features/website/schedule_spec.rb

While working on custom domains I discovered that the schedule page is not accessible to the public from a custom domain url. This is easily masked when working from the backend because the current_event gets set that way. However, the constrained domain routes don't really require the event and instead are best accessed through the current_website which holds the logic for determining which event should be accessed from a custom domain. 
You can actually see the problem right now if you try going to https://rubyconf.org/schedule and it redirects you to https://rubyconf.org/events.
Changes
=======
- removes call to current_event and require_event which results in a
redirect to root /events page when using a custom domain
- adds regression integration …

Fixes error when accessing schedule page on a custom domain

---

app/javascript/controllers/editor_controller.js
spec/features/website/page_management_spec.rb

This was an issue that Devon pointed out where all indenting was lost on the html when switching back to CodeMirror editor from tinyMCE editor.

Fixes bug where indenting is lost switching from tinyMCE to CodeMirror

---

app/controllers/proposals_controller.rb
app/models/speaker.rb
app/views/speakers/_fields.html.haml
app/views/speakers/_speaker.html.haml
db/migrate/20220727235351_add_location_to_speaker.rb
db/schema.rb

Title
Add field to support Texas vs RI speaker question
This is a quick and dirty solution that we will want to remove as soon
as RubyConf 2022 is done. We need to ask speakers where they feel most
comfortable giving their talk, and the extra field that the CFP actually
supports is open ended rather than being constrained to options.

Add field to support Texas vs RI speaker question

---

README.md
app/controllers/proposals_controller.rb
app/models/speaker.rb

Add options to indicate preference of Houston vs Mini, or only one
* We want to add options to indicate preferences, or only speaking at a specific conference
Changes
=======
* Add two more options, and two more tags
Here are screenshots of the change:
The first image shows the review view of proposals for all four types, and also one proposal for Houston created pre change (tag stays Houston):
The second image shows the author view of the dropdown when submitting a CFP:

Add options to indicate preference of Houston vs Mini, or only one

---

app/models/speaker.rb

I need to add the keynote talks and don't want to mess with tihs additional field. The CFP is closed so we do not need this validation at the moment.

Disable houston speaker field validation

---

app/models/sponsor.rb
spec/features/staff/sponsor_spec.rb

RailsConf doesn't have a Diamond sponsorship tier, but RubyConf does.
We've already sold one of these and need to add it to the website.
Adding `diamond` to `Sponsor::TIERS`

Add diamond tier to sponsor options

---

app/assets/stylesheets/themes/default/schedule.scss

🟢 - Ready for Review
**Flex schedule sub navigation to column on smaller screens**
As a user, when viewing the schedule page on a smaller screen, the schedule sub navigation shouldn't run off the screen. 
Changes
=======
Added a slightly smaller breakpoint, to the schedule CSS. 
Breakpoint adds a rule to display the Schedule Sub nav as a column on smaller screens. 
Who doesn't love a preview 
=====================

Flex schedule sub navigation to column on smaller screens

---

config/application.rb

because CFP App 1.0 used to store proposals.proposal_data as a serialized AC::Parameters.
This follows up d70de792294b035b205ebadcc8ff0b5922711e75 and fixes
`Psych::DisallowedClass: Tried to load unspecified class: ActionController::Parameters` error that occurs when trying to show proposals that are posted on CFP App Version 1.
I know that Ruby Central folks may have never seen this error since you gave up migrating the V1 data to V2 and just abandoned them, but for those who somehow migrated the old data to V2 like we did for our conference RubyKaigi, I chose to upstream this patch instead of just updating our `proposal_data` in our DB to be normal Hash objects.

proposals.proposal_data may include serialized AC::Parameters as well

---

db/migrate/20200223215131_create_versions.rb

This patch manually edits a broken migration file introduced via a9916717f2e297e4e4dd7eb57ea3865f2e03a8a0.
Since the hashrocket here will be treated as a Hash object literal rather than a kwarg under recent versions of Ruby, which will end up with creating broken schema.rb with the following diff via `db:migrate`.
```diff
-    t.string "item_type", null: false
+    t.string "item_type"
+    t.string "{:null=>false}"
```

Avoid using hashrocket for a kwarg in a migration file

---

app/models/room.rb
spec/models/room_spec.rb

Currently, rooms.name is constrained to be unique within the whole database, but in the real world, conference venues tend to name their room very similarly, for instance, "Room A, Room B, Room C..." or "101, 102, 103...". So we have to somehow workaround on cfp-app by prefixing or suffixing year or something.
I don't think there's any use case that requires the Room names to be unique across the years, thus this attribute doesn't have to be DB unique but should better be unique per event.

Let Room name be unique within each event

---

.circleci/config.yml

CircleCI seems to be running again now, https://app.circleci.com/pipelines/github/rubycentral/cfp-app
but currently it's failing to install ChromeDriver. https://app.circleci.com/pipelines/github/rubycentral/cfp-app/449/workflows/7f8efd7f-e9b1-4a67-98a0-d1a0684b1968/jobs/454
Let's update Browser-Tools version and see if it works.

Use newer Browser-Tools Orb on CircleCI

---

app/models/proposal.rb

Or this scope causes "PG::AmbiguousColumn: ERROR:  column reference "confirmed_at" is ambiguous" when joined with another table that has `confirmed_at` column.
Example
Proposal.joins(speakers: :user).confirmed
=> ActiveRecord::StatementInvalid (PG::AmbiguousColumn: ERROR:  column reference "confirmed_at" is ambiguous)

Prefer Arel based AR DSL over SQL string in scopes

---

Gemfile.lock

Update selenium-webdriver only, fail feature specs by "wrong number of arguments"
see also #407

Update capybara and selenium-webdriver

---

spec/controllers/proposals_controller_spec.rb
spec/controllers/staff/grids/time_slots_controller_spec.rb
spec/controllers/staff/proposals_controller_spec.rb
spec/controllers/staff/rooms_controller_spec.rb
spec/controllers/staff/time_slots_controller_spec.rb
spec/factories/proposals.rb
spec/factories/users.rb
spec/features/staff/sponsor_spec.rb
spec/features/website/configuration_spec.rb
spec/features/website/program_spec.rb
spec/features/website/schedule_spec.rb
spec/mailers/comment_notification_mailer_spec.rb
spec/models/proposal_spec.rb
spec/models/public_comment_spec.rb
spec/models/teammate_spec.rb
spec/policies/page_policy_spec.rb
spec/policies/program_session_policy_spec.rb
spec/policies/proposal_policy_spec.rb
spec/policies/speaker_policy_spec.rb
spec/policies/website_policy_spec.rb
spec/support/shared_examples/a_proposal_page.rb

The factory callbacks defined `spec/factories/users.rb` are wrong. Fix it and re-enable skipped test cases that failed by the wrong factory callbacks.

Fix skipped specs by wrong factory callbacks

---

.github/workflows/test.yml

Here's another attempt to fix "You must have ImageMagick or GraphicsMagick installed" error on CI... https://github.com/rubycentral/cfp-app/actions/runs/12268483070/job/34230381458#step:7:814

"You must have ImageMagick or GraphicsMagick installed"

---

app/decorators/proposal_decorator.rb

for the servers that offloads SSL and runs with http:// locally.

Let the confirmation link in the accept mail be https://

---

app/controllers/admin/events_controller.rb

Currently, admin/events are ordered by id asc, which means old event comes first, but for organizations having many events (we at RubyKaigi have 17 events), it sometimes feels a bit hard to find the one we're currently focusing on. Instead, it'd be better if simply newest one always comes at the very top of the list.

Order admin events by archived and id desc

---

spec/features/staff/proposals_spec.rb

So let's just get rid of an outdated feature spec.

Staff cannot edit proposals since 8864620f593b3d9e7aa176d8d1b00e0d1366a4c0

---

spec/factories/program_sessions.rb
spec/features/staff/organizer_manages_program_session_spec.rb
spec/features/staff/speakers_spec.rb

because Speaker.belongs_to :event.
This patch brings some pending specs back to life by fixing broken factories.

Speaker factory needs an Event

---

app/controllers/proposals_controller.rb
app/controllers/staff/program_sessions_controller.rb
app/controllers/staff/time_slots_controller.rb
app/decorators/event_decorator.rb
app/models/event.rb
app/models/notification.rb
app/models/proposal.rb
spec/factories/events.rb
spec/factories/notifications.rb
spec/factories/pages.rb
spec/features/admin/event_spec.rb
spec/features/event_spec.rb
spec/features/proposal_spec.rb
spec/models/event_spec.rb
spec/models/notification_spec.rb
spec/models/proposal_spec.rb

This patch replaces all occurrences of deprecated `DateTime` to `Time`.

DateTime => Time

---

app/decorators/event_decorator.rb
app/models/event.rb
db/seeds.rb
spec/controllers/proposals_controller_spec.rb
spec/factories/events.rb
spec/factories/notifications.rb
spec/factories/pages.rb
spec/features/admin/event_spec.rb
spec/features/event_spec.rb
spec/features/proposal_spec.rb
spec/models/notification_spec.rb
spec/models/proposal_spec.rb

This patch replaces all occurrences of `Time.now` to timezone aware `Time.current`.

Time.now => Time.current

---

Gemfile
Gemfile.lock

mimemagic version has been locked since bfe03509f766a67c47e5ed5df2111b5fe1e932b7 without explaining why this revision, so let's try updating to the newest released gem and see what's going to happen.

budnle u mimemagic

---

app/views/staff/grids/show.html.haml

with {locale: [:en], formats: [:html], variants: [], handlers: [:raw, :erb, :html, :builder, :ruby, :haml, :jbuilder]
I don't understand why this doesn't happen in the tests (maybe this page is not covered?), but we're seeing this in production.

"Missing template staff/grids/schedule.json.jbuilder"

---

app/assets/javascripts/proposal.js
app/controllers/proposals_controller.rb
app/views/proposals/_contents.html.haml
app/views/proposals/parse_edit_field.js.erb

because id won't be unique when having collection inputs like radio_buttons/checkboxes.

Use field name instead of id for parse_edit_field

---

app/controllers/proposals_controller.rb
app/views/proposals/finalized_notification.html.erb
config/routes.rb

This action is no longer in use since b4ff3fb70af5645c799f5966a88ff7cfaadeaaca, I guess.

Removing unused action proposals/finalized_notification

---

app/controllers/proposals_controller.rb
app/views/proposals/parse_edit_field.js.erb

Because this would define all helper methods as action_methods. Instead, let's call helper methods in view files as usual.

Avoid including ApplicationHelper in a controller

---

app/controllers/application_controller.rb

Here's another non-action_method that is mistakenly defined as a public method in ApplicationController.

after_sign_in_path_for is not an action_method

---

app/controllers/application_controller.rb
app/models/bulk_time_slot.rb
app/models/proposal.rb
app/models/schedule.rb
app/models/time_slot.rb

This patch fixes duplicated method definitions that emits Ruby warnings.

Duplicated method definitions

---

app/decorators/event_decorator.rb
app/models/event.rb
app/models/user.rb

This patch reduces `select count` queries by reusing counted values and by changing the queries from `count` to `exists?`.

Reduce `select count` queries

---

app/models/proposal.rb

Calling this association causes:
> ERROR:  column time_slots.proposal_id does not exist (ActiveRecord::StatementInvalid)

Proposal.not.has_one :time_slot

---

app/models/session_format.rb

Calling this association causes:
> ERROR:  column time_slots.session_format_id does not exist

SessionFormat.not.has_many :time_slots

---

app/models/speaker.rb

Calling this association causes:
> ERROR:  column program_sessions.speaker_id does not exist

Speaker.not.has_many :program_sessions

---

spec/system/proposal_spec.rb

This fixes sporadic test failures.

Assert page contents before asserting anything else

---

app/controllers/profiles_controller.rb
app/controllers/proposals_controller.rb
spec/support/shared_examples/an_incomplete_profile_notifier.rb

This patch fixes an issue that some flash messages (that could include user inputs) weren't properly html-escaped.

Properly escape validation error messages

---

app/views/proposals/_form.html.haml

Here's a trivial optimization on proposal form that retrieves track collection via pluck instead of select(*) + map.

Proposal form optimization

---

.irbrc
Gemfile
Gemfile.lock

Recent versions of irb are truly amazing without gems like this, and since we've updated .ruby_version of this app to the newest released Ruby, now we're on the newest irb.

Unbundle amazing_print

---

app/controllers/application_controller.rb

This would possibly reduce one query per each page.

Try omitting Event query when `@current_event` is already set

---

app/controllers/proposals_controller.rb

This patch fixes a broken SQL introduced via 1fd9052bfabc18380edc3fa384cd3f5a3e655882 that selects * when including some models that are not joined. We should have selected `proposals.*` instead.

Fix broken SQL in my-proposals
