README.md
I found another markdown formatting error
=> Fixing markdown formatting issue

spec/mailers/participant_invitation_mailer_spec.rb, spec/mailers/previews/participant_invitation_preview.rb
No markdown changes made; only moved mailer preview to spec folder because project uses rspec
=> #11 moved mailer test preview to spec folder

app/assets/javascripts/proposal.js, app/decorators/proposal_decorator.rb, app/models/proposal.rb, app/views/proposals/_contents.html.haml
- set character limit of 60 on proposal title
- alert for title and abstract when character limit is exceeded
=> #17 Proposal UI enforces proposal title length

README.md
Follow up of f55f8d0. : )
<kbd>[View rendered README.md](https://github.com/JuanitoFatas/cfp-app/blob/10d31ead9689dd009729368591a24d7499da5e73/README.md)</kbd>
=> Update version of Rails in README.md [ci skip]

app/controllers/admin/events_controller.rb, app/controllers/application_controller.rb, spec/support/feature_helper.rb
> Adequate Record is a set of performance improvements in Active Record
that makes common find and find_by calls and some association queries
up to 2x faster.
> http://guides.rubyonrails.org/4_2_release_notes.html#adequate-record
Spotted while browsing the source code. : )
=> Change find_by_id to find_by(id: ...) to improve performance

app/assets/stylesheets/_navbar.css.scss, app/assets/stylesheets/application.css.scss
Added a grey background to the dropdown navbar for when the site's viewed from a smaller screen, making it easier to read.  Also changed the dropdowns within the menu to be a dark grey instead of black when they are clicked.
=> Add navbar background for mobile.

app/assets/stylesheets/_base.css.scss, app/views/organizer/proposals/_form.html.haml, app/views/organizer/proposals/edit.html.haml
Made page header more legible and easy to understand; did some layout cleanup.
=> ui cleanup organizer/proposal/edit page

app/assets/stylesheets/_base.css.scss, app/assets/stylesheets/_proposal.css.scss, app/models/comment.rb, app/models/event.rb, app/models/internal_comment.rb, app/models/invitation.rb, app/models/notification.rb, app/models/participant.rb, app/models/participant_invitation.rb, app/models/person.rb, app/models/proposal.rb, app/models/public_comment.rb, app/models/room.rb, app/models/service.rb, app/models/tagging.rb, app/views/proposals/index.html.haml, db/schema.rb
Moved submit button, moved submitted flag, broke up proposal list with hr.
=> Improved styling of proposals list

app/views/organizer/proposals/_form.html.haml
I added an if statement because Custom Fields alone with no form input doesn't make sense.
=> Custom fields alignment

spec/models/proposal_spec.rb
See 2d7f87f1483a8447258f01aee54a48d0bdab10b1
=> Fix the failing test, validating against our increased maxlength

app/views/teammate_invitation_mailer/create.md.erb
=> Fix typo in team invitation mailer.

Gemfile, Gemfile.lock, app/models/session_format.rb, spec/features/staff/event_config_spec.rb, spec/features/staff/teammates_spec.rb
* Workaround a recurring issue in chromedriver where input field values
are truncated
* Email address not cleaned between tests, so generate a random one
* Description input expected to be limited to 250 characters
* Replace deprecated chromedriver gem
=> Fix failing tests

README.md, app/views/devise/shared/_links.html.erb, app/views/pages/current_styleguide.html.haml, spec/features/receive_speaker_invitation_spec.rb, spec/features/staff/teammate_invitation_spec.rb, vendor/assets/javascripts/jquery.mentionsInput.js
GitHub is not Github. https://github.com/about
=> Spell GitHub correctly

app/views/staff/proposals/bulk_finalize.html.haml
=> Add note about heroku worker for bulk finalize

config/environments/production.rb, config/initializers/devise.rb
This pull request enables using non-SendGrid mail providers while maintaining compatibility with existing installations.
=> Makes it possible to configure the SMTP settings

README.md, app.json, app/assets/javascripts/cable.js, app/assets/javascripts/staff/proposals.js, app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, app/channels/notifications_channel.rb, app/controllers/staff/proposals_controller.rb, app/jobs/bulk_finalize_job.rb, app/views/staff/proposals/bulk_finalize.html.haml, config/cable.yml, config/environments/development.rb, config/environments/production.rb, config/routes.rb
Add ActionCable to emit status messages to know where bulk finalize is
in the process of finalizing. Once a status has been finalized that row
is removed from the table. The interaction is all asynch now.
This fixes #179 and #182
=> Bulk Finalize visibility

.circleci/config.yml, CONTRIBUTING.md, README.md
* Continuous integration is a good way to ensure the app is building properly and the test suite is green
Changes
=======
* Add a `.circleci/config.yml` file.
Minor
=====
* Fix remaining master > main corrections
* Add a note about draft PRs
=> Add config file for CircleCI

.github/workflows/main.yml
* We should be able to deploy automatically from `main` to staging once merge is complete
Changes
=======
* Added a workflow config file
* Reference: https://github.com/marketplace/actions/deploy-to-heroku
=> Add a GitHub Workflow config file

Gemfile, Gemfile.lock
* App is down
Changes
=======
* Add back gems which were removed in `mail` gem (see [this SO post](https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp))
=> Add missing gems

.irbrc, Gemfile, Gemfile.lock, spec/features/website/page_viewing_spec.rb
* We should monitor our website for errors and outages
Changes
=======
* Add honeybadger gem
Minor
=====
* Add amazing_print gem for debugging
* Add a context block for the custom subdomain specs
* Add an .irbrc
https://app.asana.com/0/1202521178011206/1202602453290577/f
=> Add Honeybadger

app/models/invitation.rb
=> More houston or providence hackery

app/models/speaker.rb
This was a request from Twitter:
https://twitter.com/monfresh/status/1562459033080299520
Title
*
Changes
=======
*
Minor
=====
*
https://link.to/task_tracker_card
=> Add Middle Eastern/North African ethnicity

config/application.rb
by requiring 'logger' earlier than 'rails'...
https://github.com/rubycentral/cfp-app/actions/runs/12996948763/job/36246820920?pr=443
=> Work around on missing logger problem

spec/features/proposal_spec.rb, spec/features/staff/organizer_manages_program_session_spec.rb
These ones are passing now, perhaps due to recent factory fixes.
=> Unpend some passing specs

bin/rails, bin/rake, bin/setup, bin/yarn, config.ru, config/application.rb, config/boot.rb, config/environment.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/backtrace_silencers.rb, config/initializers/content_security_policy.rb, config/initializers/new_framework_defaults_6_1.rb, config/initializers/permissions_policy.rb, config/puma.rb, db/migrate/20250215081513_add_service_name_to_active_storage_blobs.active_storage.rb, db/migrate/20250215081514_create_active_storage_variant_records.active_storage.rb, db/schema.rb
=> rails app:update

config/application.rb
```
active_record.cache_versioning = true
action_dispatch.use_authenticated_cookie_encryption = true
active_support.use_authenticated_message_encryption = true active_support.hash_digest_class = ::Digest::SHA1
action_controller.default_protect_from_forgery = true
action_view.form_with_generates_ids = true
```
=> Load Rails 5.2 framework defaults

Gemfile, Gemfile.lock
=> bundle u haml-rails

app/controllers/proposals_controller.rb
Thank you @koic for reporting this!
=> Order my-proposals by event desc

spec/decorators/proposal_decorator_spec.rb, spec/models/proposal_spec.rb, spec/system/website/configuration_spec.rb
Please don't pollute the world.
=> Don't include anything on TOPLEVEL

app/helpers/application_helper.rb
This fixes potentially broken or danger markups in flash messages.
=> Safely join unsafe strings in flash message

app/decorators/event_decorator.rb, app/views/events/show.html.haml
Here are some optimizations for events#show.
=> events#show query optimizations

app/models/notification.rb, app/views/layouts/nav/_notifications_list.html.haml
This patch reduces queries for displaying notifications.
=> Notification optimizations

app/helpers/application_helper.rb
Previous code selects all proposal records and pending invitation records that are never used here.
=> Use EXISTS query instead of SELECT *

app/controllers/proposals_controller.rb, app/models/proposal.rb, app/views/proposals/_comments.html.haml, app/views/proposals/show.html.haml, app/views/speakers/_speaker.html.haml
This patch reduces queries from proposals#show in various ways.
=> proposals#show optimizations

app/views/staff/time_slots/_time_slot.html.haml
This follows up 7389ed94627aa6fa534c81cb20590a7cfe5bf71b.
=> Time#to_s => to_fs

app/controllers/proposals_controller.rb, app/views/proposals/index.html.haml
This patch optimizes my-proposals.
=> my-proposals optimization

app/assets/javascripts/cable.js
> – please update your reference before Rails 8
=> DEPRECATION: action_cable.js has been renamed to actioncable.js

app/models/event_stats.rb, app/models/proposal.rb
This patch speeds up the dashboard by optimizing queries.
=> Dashboard optimizations

app/decorators/event_decorator.rb
Here's a trivial improvement on events#show.
=> events#show optimization

app/helpers/application_helper.rb, app/models/teammate.rb, app/views/layouts/_navbar.html.haml
Here's a patch that reduces queries for showing navbar. I know that this somewhat worsens the code readability, but it's worth because this affects on all pages.
=> navbar optimization

app/controllers/concerns/activate_navigation.rb, config/routes.rb
No need to define a custom route. Just use default proposals resource.
=> event_event_proposals_path => event_proposals_path

app/controllers/concerns/activate_navigation.rb
It's obviously safer and more maintainable.
=> Use Rails' built-in polymorphic URL helper instead of Kernel#send

app/views/layouts/_navbar.html.haml, config/routes.rb
Setting this envvar to a truthy value would reduce some queries when showing each page.
=> Add `DISABLE_WEBSITE` ENVVAR for hiding "website" beta
